README.md
rules/catch-or-return.js
test/catch-or-return.test.js

This change:
1. Extends the things treated as Promises to include the result of `Promise.all` etc.
2. Adds an option to change the `terminationMethod` (defaulting to `catch`).  This lets you require promise chains to be terminated with the method of your choice (e.g. `.done()`, which is common practice in most non-native Promise implementations).

Catch or return

---

rules/always-return.js
test/always-return.test.js

Throwing an error is a valid way of terminating the function passed to `then` and will result in a rejected promise.
If this PR is merged it will allow something like this:
```js
function isUserLoggedIn (username) {
return getUserByName(username).then(user => {
if (user) {
return user.isLoggedOut();
}
throw new Error('user not found');
});
}
```

Allow throw in always-return rule

---

rules/no-native.js

Sorry to be a pain, but I've found that the no-native part of this plugin does not pick up native promises in our project and I'm not 100% why.
At first I thought it might be because we're using the current version of eslint, when I saw this: https://github.com/eslint/eslint/pull/4648/files, but I've run the tests in this plugin against eslint 2 and while a bunch of them fail, the no-native ones pass. We use a huge mess of packages so trying to work out where the bad interaction/transpilation happens is a difficult task.
I've played around with the various lists of references on a scope and found that `scope.implicit.left` appears to include the native uses of `Promise` in my project, and in this plugin's tests, so I think we're going to run off this fork for now.
I thought maybe you have …

Make no-native work with ???

---

README.md
package.json
rules/always-return.js
test/always-return.test.js

This will also change the reported location of errors to the inner
function that failed to return, rather than referring to it's enclosing
Promise
I bumped up the the version number (2.0.1 -> 3.0.0) because the changed
location reporting could un-suppress linter errors that have been
suppressed with `// eslint-disable-line promise/always-return`
fixes xjamundx/eslint-plugin-promise#8
fixes xjamundx/eslint-plugin-promise#18
fixes xjamundx/eslint-plugin-promise#24

add code path analysis to always-return

---

README.md
rules/catch-or-return.js
test/catch-or-return.test.js

An array can now be passed for the terminationMethod option.
Allows use of multiple valid terminators.
Bluebird has the `asCallback` method which is also a valid terminator in addition to `catch`.

Add option for multiple terminationMethods

---

package.json

This plugin doesn't technically depend on eslint (there are no require calls to eslint, except in test).
Listing eslint as peer dependency is problematic, when this repository is not used as direct dependency, but rather required in something like https://github.com/feross/standard
Currently installation of standard results in following warnings:
```
└─┬ standard@8.5.0
├─┬ UNMET PEER DEPENDENCY eslint@3.8.1
│ ├── globals@9.12.0
│ ├── strip-bom@3.0.0
│ └── user-home@2.0.0
├── eslint-config-standard@6.2.1
├── eslint-config-standard-jsx@3.2.0
├── UNMET PEER DEPENDENCY eslint-plugin-promise@3.3.1
├─┬ eslint-plugin-react@6.4.1
│ └── jsx-ast-utils@1.3.3
├── eslint-plugin-standard@2.0.1
└─┬ standard-engine@5.1.1
├─┬ deglob@2.0.0
│ ├── run-parallel@1.1.6
│ └── uniq@1.0.1
├── find-root@1.0.0
├── …
```

Remove eslint as peer dependency

---

rules/always-return.js

Should fix the reported location for *promise/always-return* errors.
Tested with both `eslint@^2` and `eslint@^3`, but I don't know how to add it to project tests :/

Replaced 'loc' with 'node' for context.report

---

README.md
index.js
rules/lib/is-promise.js
rules/no-return-in-finally.js
test/no-return-in-finally.js

Adds a rule that disallows return statements it the callback passed to `.finally()`.
**Valid**
```javascript
myPromise.finally(function(val) {
console.log('value:', val);
});
```
**Invalid**
```javascript
myPromise.finally(function(val) {
return val;
})
```
I suggested reporting as a warning in the recommended rules since the violation likely has no ill effects.

rule: no-return-in-finally (fixes #44)

---

README.md
rules/no-return-wrap.js
test/no-return-wrap.js

Adds option to the no-return-wrap rule that was proposed in #50.
Example:
**Invalid**
```javascript
/*eslint promise/no-return-wrap: "error"*/
myPromise.then(() => {
return Promise.reject(new Error("bad thing"))
});
myPromise.then(function() { return Promise.reject(42) });
```
**Valid**
```javascript
/*eslint promise/no-return-wrap: ["error", { allowReject: true }]*/
myPromise.then(() => {
return Promise.reject(new Error("bad thing"))
});
myPromise.then(function() { return Promise.reject(42) });
```

option: add allowReject for no-return-wrap (fixes #50)

---

package.json

Looking at the [Mocha changelog](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md), I'm not seeing any breaking changes that apply to this codebase.

chore(package): update to mocha v5

---

package.json

Resolves #63
Looking at the [ESLint v4 migration guide](https://eslint.org/docs/user-guide/migrating-to-4.0.0#breaking-changes-for-plugincustom-rule-developers), I'm not seeing any breaking changes that apply to this codebase. Updating to ESLint v4 locally and running the test suite resulted in 0 failures.
If there's anything else to consider here, please let me know and I'd be happy to look into it and test further.

chore(package): update to eslint v4

---

.npmignore

When looking at https://unpkg.com/eslint-plugin-promise@3.6.0/, it seems like the `.travis.yml` file is not being ignored. This PR updates `.npmignore` to properly ignore that file when shipping this package to the npm registry.

chore: include .travis.yml in .npmignore

---

.npmrc

When running `npm install` in this codebase with npm v5, it defaults to generating a `package-lock.json` file. Setting `package-lock=false` will prevent generating this file when running `npm install`.
If you would like this file added to `.gitignore` instead, or would like to include this file in the repository, I would be glad to change this PR or open another one. 👍

chore: ignore package-lock.json

---

README.md

This PR aims to clean up the README a little bit and add a table of contents. I see this as a first step to resolving #61.
I generated the table of contents by running `npx doctoc README.md --notitle --maxlevel=3`. I wanted to set up [lint-staged](https://github.com/okonet/lint-staged) in this PR, but I had trouble installing it using Node 4 and npm 2 in my local development environment. (I'll open an issue to discuss using Node 8 and npm 5 as the preferred development environment, but continue running tests on Node 4 to continue supporting that version of Node with this ESLint plugin.)
The primary change is that all rules are documented below the **Rules** section with the following convention:
```
```
This allows for consistent documentation URLs, which now look like …

docs(readme): add table of contents

---

.eslintrc.json
.npmignore
.travis.yml
package.json
rules/always-return.js
rules/avoid-new.js
rules/catch-or-return.js
rules/lib/.eslintrc.json
rules/no-callback-in-promise.js
rules/no-native.js
rules/no-nesting.js
rules/no-promise-in-callback.js
rules/no-return-in-finally.js
rules/no-return-wrap.js
rules/param-names.js
rules/prefer-await-to-callbacks.js
rules/prefer-await-to-then.js

Resolves #61 
First step of this PR was converting each rule to export an object instead of a function using [eslint-transforms](https://github.com/eslint/eslint-transforms), specifically the [new-format-rule](https://github.com/eslint/eslint-transforms#new-rule-format) transform. I ran the following command.
```sh
$ npx eslint-transforms new-rule-format rules/*.js
```
I edited a few rules manually to add the `meta.docs.url` object, but after that I installed [eslint-plugin-eslint-plugin](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin) and enabled the [require-meta-docs-url](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/require-meta-docs-url.md) rule in the `rules/` directory. By running `npm run lint -- --fix` from the root of the …

fix: add rule documentation

---

.eslintrc.json
rules/avoid-new.js
rules/catch-or-return.js
rules/no-callback-in-promise.js
rules/no-native.js
rules/no-nesting.js
rules/no-promise-in-callback.js
rules/no-return-in-finally.js
rules/no-return-wrap.js
rules/param-names.js
rules/prefer-await-to-callbacks.js
rules/prefer-await-to-then.js
test/catch-or-return.test.js

Resolves #89 
This PR enables the [`eslint-plugin-eslint-plugin`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin) recommended configuration and resolves updating the `context.report()` API usage as well as removing a couple of duplicate test cases.

refactor: resolve eslint-plugin-eslint-plugin warnings

---

.eslintrc.json

https://eslint.org/docs/rules/strict
'use strict' is necessary in Node 4 to support block-scoped declarations (let, const).

style: enable strict eslint rule

---

.eslintrc.json
test/always-return.test.js
test/avoid-new.js
test/catch-or-return.test.js
test/no-callback-in-promise.js
test/no-native.js
test/no-nesting.js
test/no-promise-in-callback.js
test/no-return-in-finally.js
test/no-return-wrap.js
test/param-names.test.js
test/prefer-await-to-callbacks.js
test/prefer-await-to-then.js

This commit refactors the tests in the following way:
* change `var` to `const` where possible
* move most of the `parserOptions` that were declared for each test into the `RuleTester` constructor, which allows for simplifying most of the valid test cases from objects to strings (helped by enabling [`eslint-plugin/test-case-shorthand-strings`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/test-case-shorthand-strings.md)
* clean up message variable names, and when possible, prefer [object shorthand notation](https://eslint.org/docs/rules/object-shorthand)
All tests should continue to pass.

refactor: clean up tests

---

.eslintrc.json
rules/always-return.js
rules/catch-or-return.js
rules/lib/has-promise-callback.js
rules/lib/is-callback.js
rules/lib/is-inside-callback.js
rules/lib/is-inside-promise.js
rules/lib/is-named-callback.js
rules/lib/is-promise.js
rules/no-callback-in-promise.js
rules/no-native.js
rules/no-nesting.js
rules/no-promise-in-callback.js
rules/no-return-in-finally.js
rules/no-return-wrap.js
rules/param-names.js
rules/prefer-await-to-callbacks.js

https://eslint.org/docs/rules/prefer-const
let and const better communicate if a variable is reassigned, and it is
possible to use them in all files since 'use strict' is enabled (#100).

style: enable prefer-const rule

---

.eslintrc.json
rules/catch-or-return.js

https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/docs/rules/prefer-placeholders.md
This seems like a good practice. 👍

style: enable prefer-placeholders rule

---

.eslintrc.json
rules/always-return.js
rules/avoid-new.js
rules/catch-or-return.js
rules/lib/get-docs-url.js
rules/no-callback-in-promise.js
rules/no-native.js
rules/no-nesting.js
rules/no-promise-in-callback.js
rules/no-return-in-finally.js
rules/no-return-wrap.js
rules/param-names.js
rules/prefer-await-to-callbacks.js
rules/prefer-await-to-then.js

Documentation update
This adds a helper to lib and uses the version present in package.json for generating the URL to tagged version of the rule documentation. I think this is good because the documentation will match the version the user has installed. This way, even if a rule is changed or removed in the future, the user can find the documentation with ease.
Note: The rule `eslint-plugin/require-meta-docs-url` cannot be used with a function which would return the URL(see [not-an-aardvark/eslint-plugin-eslint-plugin#58](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/58)) so I have disabled it.

docs: Use link to tagged version for rule docs

---

README.md
docs/rules/always-return.md
docs/rules/avoid-new.md
docs/rules/catch-or-return.md
docs/rules/no-callback-in-promise.md
docs/rules/no-native.md
docs/rules/no-nesting.md
docs/rules/no-promise-in-callback.md
docs/rules/no-return-in-finally.md
docs/rules/no-return-wrap.md
docs/rules/param-names.md
docs/rules/prefer-await-to-callbacks.md
docs/rules/prefer-await-to-then.md
rules/lib/.eslintrc.json
rules/lib/get-docs-url.js

This is the first step listed in #109 of migrating rule documentation from the README to the `docs/rules` directory. This will allow for adding more documentation for each rule without making the README too large.

docs: migrate rule documentation to docs/rules

---

CHANGELOG.md

This PR executes prettier on the changelog. A v3.7.0 release is coming up soon, and I wanted a separate commit for prettying up this file, so that the 3.7.0 changelog update had a smaller diff.

docs: prettify changelog

---

README.md
__tests__/no-new-statics.js
docs/rules/no-new-statics.md
index.js
rules/lib/is-promise.js
rules/lib/promise-statics.js
rules/no-new-statics.js

Resolves #75
Hoping to continue discussion from #75 to solidify this feature.
For now, I've created a new rule named `no-new-statics`, which warns if you call any of the Promise static methods with `new`. I'm open to new naming or including it in another rule, if that would be more appropriate. Feedback appreciated. 😄

feat(rule): add no-new-statics rule

---

README.md
__tests__/valid-params.js
docs/rules/valid-params.md
index.js
rules/valid-params.js

Resolves #47 
As of now this rule simply checks how many arguments were supplied to the various `Promise` functions. If the length of arguments is invalid, it will report that as a lint violation. See the tests for examples.
There are a couple of other issues (#3, #60) that I could see being rolled into this `valid-params` rule. What are your thoughts on that? I think those could be separate PRs, but some feedback on those ideas being included in this rule / any rule would be great. 👍

feat(rule): add valid-params rule

---

docs/rules/prefer-await-to-then.md

Adds valid and invalid examples to `prefer-await-to-then` rule documentation.

docs: add examples to `prefer-await-to-then`

---

docs/rules/no-nesting.md

Added valid and invalid examples to `no-nesting` rule documentation

docs: add no-nesting examples

---

.npmrc
.prettierignore
.travis.yml
package-lock.json

This PR introduces a `package-lock.json` file. Some updates to `@babel/code-frame` were causing build failures (as Jest includes this as a dependency). Locking to version 7.0.0-beta.46 resolved the issue on Node 4.
I think introducing a lockfile makes sense. I'm not sure what the long term ramifications of Jest and Babel are and how Node 4 will be fully supported moving forward. This works for now, but is something to keep an eye on.
I also made some changes to the Travis build script to use [npm ci](https://docs.npmjs.com/cli/ci) for installing modules.

chore(package): add package-lock.json

---

README.md
index.js

feat: turn off avoid-new in recommended configuration

---

rules/lib/is-promise.js
rules/lib/promise-statics.js
rules/no-new-statics.js

This is a small optimization to lookup Promise static method names from an object (O(1)) instead of an array (O(n)).

refactor: lookup promise statics from object instead of array

---

docs/rules/no-return-wrap.md
docs/rules/param-names.md

Fixed incorrect description of document.
The description of `param-names` was listed in` no-return-wrap`.

Fixed incorrect description of document.

---

README.md
__tests__/no-new-statics.js
rules/no-new-statics.js

This adds autofixing to the `no-new-statics` rule. Not 100% sure about adding this, but wanted to get a PR up for it.

feat(fixer): add fixer to no-new-statics rule

---

README.md

Following up on discussion in #139, I think it might be good to explicitly call out the ordering aspect of `param-names` in your `README` table.  It's clear when you read https://github.com/xjamundx/eslint-plugin-promise/blob/master/docs/rules/param-names.md, but I know *I* missed that when I only looked at the `README` summary.

Fix #139: make it more clear that param-names includes ordering

---

index.js

Ensure eslint-plugin-promise is loaded when using recommended settings.
When using promise/recommended-config, eslint-plugin-promise wasn't actually including the `plugin` in the configuration, only the `rules`.

Update recommended settings

---

__tests__/catch-or-return.js
docs/rules/catch-or-return.md
package-lock.json
rules/catch-or-return.js

This adds the `allowFinally` option to `catch-or-return` as described in #158.  This allows the use of `.finally()` _after_ a Promise chain has been "caught".
Closes #158

Add allowFinally option to catch-or-return rule

---

__tests__/no-return-wrap.js
rules/no-return-wrap.js

* Fixed that `no-return-wrap` does not work if type is not "ExpressionStatement".
(ex. "ReturnStatement" argument,"CallExpression" argument)
* Fixed that `no-return-wrap` does not work if multiple "ExpressionStatement" exists in the ancestor of "ReturnStatement".
I changed to search for the ancestor of "FunctionExpression" closest to "ReturnStatement" and to check if the parent node of that "FunctionExpression" is `Promise`.
Close #150

Fixed that `no-return-wrap` does not work if type is not "ExpressionStatement".

---

docs/rules/no-nesting.md

The Invalid examples were also violating the rule `always-return`, but now they don't.

Simplify Invalid examples for the no-nesting rule

---

__tests__/no-return-wrap.js
rules/always-return.js
rules/lib/has-promise-callback.js
rules/no-return-wrap.js

Checks CallExpressions that are direct descendants of ArrowFunctionExpressions (meaning that the arrow function returns a CallExpression without braces) and reports if it is `Promise.resolve` or `Promise.reject`.
Fixes #193.

fix(no-return-wrap): fix it not reporting for arrow functions without braces

---

docs/rules/no-new-statics.md
docs/rules/param-names.md
rules/param-names.js

- docs(no-new-statics): add mention of the rule being fixable
- docs(param-names): Remove `fixable` reference as not currently fixable
- fix(param-names): avoid including `fixable: code` when not fixable
Per the eslint docs at https://eslint.org/docs/developer-guide/working-with-rules#options-schemas
> Omit the fixable property if the rule is not fixable.

Fixable fix

---

rules/lib/get-docs-url.js

When use eslint's node.js api to get rule's metadata(CLIEngine.getRules()), unfortunately, this plugin's rule's doc url is invalid(404). for example:
[https://github.com/xjamundx/eslint-plugin-promise/tree/v4.1.1/docs/rules/prefer-await-to-then.md](https://github.com/xjamundx/eslint-plugin-promise/tree/v4.1.1/docs/rules/prefer-await-to-then.md)
which should be modified as 
[https://github.com/xjamundx/eslint-plugin-promise/blob/master/docs/rules/prefer-await-to-then.md](https://github.com/xjamundx/eslint-plugin-promise/blob/master/docs/rules/prefer-await-to-then.md)
@xjamundx @macklinu   please take a look at this:)

fix(rulesMeta): update invalid rule docs url in rule's metadata

---

README.md
__tests__/prefer-await-to-then.js
docs/rules/prefer-await-to-then.md
rules/prefer-await-to-then.js

Flag `catch()` and `finally()` usages in the `prefer-await-to-then` rule

prefer-await-to-then should flag promise.catch/finally as well

---

__tests__/prefer-await-to-callbacks.js
rules/prefer-await-to-callbacks.js

Now shows an error if callback has "error" as the first param.
Original if statement only checked the first param name was "err". Now it also checks for "error"

included check for string literal 'error'

---

.github/workflows/CI.yml

As requested by @voxpelli in https://github.com/xjamundx/eslint-plugin-promise/pull/219#issuecomment-979891417

chore(CI): support testing against multiple ESLint versions

---

package-lock.json
package.json
rules/always-return.js
rules/avoid-new.js
rules/catch-or-return.js
rules/no-callback-in-promise.js
rules/no-native.js
rules/no-nesting.js
rules/no-new-statics.js
rules/no-promise-in-callback.js
rules/no-return-in-finally.js
rules/no-return-wrap.js
rules/param-names.js
rules/prefer-await-to-callbacks.js
rules/prefer-await-to-then.js
rules/valid-params.js

Resubmission of #230
CC/ @xjamundx
---
As requested by @voxpelli in https://github.com/xjamundx/eslint-plugin-promise/pull/219#issuecomment-979891417

chore: update `eslint-plugin-eslint-plugin` to latest

---

.github/workflows/CI.yml
package-lock.json
package.json

ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉
devDependency compatibility with ESLint 8:
---
Closes #218

feat: support ESLint 8.x

---

__tests__/no-native.js
package-lock.json
package.json
rules/no-native.js

- Other: added tests for `@typescript-eslint/parser` in the `no-native` rule
1. Installed `typescript` and `@typescript-eslint/parser` as a dev dependency.
2. Removed the `istanbul ignore next` directive in the `no-native` source file.
3. Configured a second rule tester with `@typescript-eslint/parser` in the `no-native` test file.
4. Ran both the original rule tester and the TypeScript rule tester in the test file.
5. Bumped the version number from `6.0.0` to `6.0.1` in `package.json` and `package-lock.json`.

feat: add tests for @typescript-eslint/parser

---

package.json

chore: lint all files by default and add `--report-unused-disable-directives` flag
Linting all by default, and later adding an `.eslintignore` if necessary, allows IDEs to avoid showing errors on intentionally ignored files.

linting: check all files by default and add `--report-unused-disable-directives`

---

.npmignore
README.md

Update build badge now that GitHub Actions is used. When removing the old reference to .travis.yml, saw that there were some other dotfiles that weren't ignored right now

chore: remove old Travis CI badge and update .npmignore

---

.github/workflows/CI.yml

ESlint 7 doesn't offcially support Node 18, but it can be added to the ESLint 8 matrix

ci: Add Node 18 for ESlint 8 only

---

CHANGELOG.md
__tests__/no-promise-in-callback.js
docs/rules/no-callback-in-promise.md
rules/no-native.js

Used cSpell to find a few minor typos

fix: minor typos

---

.github/workflows/CI.yml

Follow-up of #360
ESLint v7 supports `>=12`, so that's also v18

chore: also test ESLint v7 on Node v18

---

__tests__/no-nesting.js
rules/lib/has-promise-callback.js
rules/no-nesting.js

This PR fixes the `no-nesting` rule to not report when there are variable references that cannot resolve the nesting.
close #123

fix(no-nesting): nested references vars in closure

---

__tests__/prefer-await-to-then.js
rules/prefer-await-to-then.js

This PR fixes the prefer-await-to-then rule to not report member access without calling.
close #163

fix(prefer-await-to-then): member access without call

---

__tests__/always-return.js
rules/always-return.js

This PR modifies the always-return rule to correctly use codepath analysis.
This change also reduced unnecessary branching.
close #213

fix(always-return): false positives for logical expr

---

__tests__/always-return.js
docs/rules/always-return.md
rules/always-return.js

This PR adds `ignoreLastCallback` option to `always-return` rule.
If `ignoreLastCallback: true`, the last `then()` callback in a promise chain does not warn if it does not have a `return`.
close #59

feat(always-return): add `ignoreLastCallback` option

---

__tests__/param-names.js
docs/rules/param-names.md
rules/param-names.js

This PR adds `resolvePattern` and `rejectPattern` option to `param-names` rule.
close #206

feat(param-names): add `resolvePattern` and `rejectPattern` option

---

__tests__/no-multiple-resolved.js
docs/rules/no-multiple-resolved.md
index.js
rules/lib/is-promise-constructor.js
rules/no-multiple-resolved.js
rules/param-names.js

This PR adds `no-multiple-resolved` rule that warns of paths that resolve multiple times in executor functions that
Promise constructors.
close #222

feat: add `no-multiple-resolved` rule

---

__tests__/catch-or-return.js
__tests__/no-new-statics.js
__tests__/no-promise-in-callback.js
__tests__/valid-params.js
rules/lib/promise-statics.js
rules/valid-params.js

This PR makes the plugin support for `Promise.allSettled()` and `Promise.any()`.
Specifically, the following rules now support new methods:
- catch-or-return
- no-new-statics
- no-promise-in-callback
- valid-params
close #367

feat(catch-or-return,no-new-statics,no-promise-in-callback,valid-params): add support for `Promise.allSettled()` & `Promise.any()`

---

README.md

This PR adds a no-multiple-resolved rule link to the README. I forgot to add it in #369 😓

docs(README): add no-multiple-resolved rule link

---

.github/workflows/CI.yml
package-lock.json
package.json

Just like I did in https://github.com/eslint-community/mysticatea__eslint-plugin/pull/1 & https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/313

chore(CI): simplify testing strategy

---

.github/workflows/CI.yml
package.json

This branch depends on on #378
Closes #354
---
This PR is inspired by what I did for `@mysticatea/eslint-plugin` in https://github.com/eslint-community/mysticatea__eslint-plugin/pull/8 & for `eslint-plugin-eslint-plugin` in https://github.com/eslint-community/eslint-plugin-eslint-plugin/pull/314

chore(CI): add automatic release

---

__tests__/no-multiple-resolved.js
rules/no-multiple-resolved.js

This PR fixes the `promise/no-multiple-resolved` rule to fix a false positive when the last expression in a try block is a call to resolve with.
close #382

fix(no-multiple-resolved): false positives when the last expression in a try block is a call to resolve

---

.github/workflows/ci.yml
__tests__/always-return.js
__tests__/avoid-new.js
__tests__/catch-or-return.js
__tests__/no-callback-in-promise.js
__tests__/no-multiple-resolved.js
__tests__/no-native.js
__tests__/no-nesting.js
__tests__/no-new-statics.js
__tests__/no-promise-in-callback.js
__tests__/no-return-in-finally.js
__tests__/no-return-wrap.js
__tests__/param-names.js
__tests__/prefer-await-to-callbacks.js
__tests__/prefer-await-to-then.js
__tests__/rule-tester.js
__tests__/valid-params.js
package-lock.json
package.json
rules/lib/eslint-compat.js
rules/no-callback-in-promise.js
rules/no-multiple-resolved.js
rules/no-native.js
rules/no-nesting.js
rules/no-promise-in-callback.js
rules/no-return-wrap.js
rules/prefer-await-to-callbacks.js
rules/prefer-await-to-then.js

This is phase 1 of getting eslint v9 working.
The features this implements are:
1. Use the sourceCode form of `getAncestors`
1. Use the sourceCode form of `getScope`
1. Allow for the `RuleTester` class to be usable in both eslint v7, v8 and v9.
---
As you may be able to tell, I copied a few files over from eslint-plugin-n (Specifically from https://github.com/eslint-community/eslint-plugin-n/pull/161) (@aladdin-add Thank you for the prior art 🙏)
---
This is one part of #449.

feat: Resolve `getAncestors` and `getScope` calls in eslint v9

---

.github/workflows/ci.yml
rules/no-multiple-resolved.js

This PR changes the no-multiple-resolved rule to work with eslint v9.
Fixes #472
Follow up for #466

feat: add support for eslint v9

---

.eslint-doc-generatorrc.js
README.md
__tests__/index.js
docs/rules/always-return.md
docs/rules/avoid-new.md
docs/rules/catch-or-return.md
docs/rules/no-callback-in-promise.md
docs/rules/no-native.md
docs/rules/no-nesting.md
docs/rules/no-new-statics.md
docs/rules/no-promise-in-callback.md
docs/rules/no-return-in-finally.md
docs/rules/no-return-wrap.md
docs/rules/param-names.md
docs/rules/valid-params.md
index.js
package-lock.json
package.json

This PR adds support for flat config.
Close #449
#478 needs to be merged first.

 feat: add support for flat config

---

rules/always-return.js
rules/avoid-new.js
rules/no-nesting.js
rules/no-new-statics.js
rules/no-promise-in-callback.js
rules/no-return-in-finally.js
rules/param-names.js
rules/prefer-await-to-then.js
rules/valid-params.js

Migrate all `message` to `messageId` (for the update to eslint-plugin-eslint-plugin)
(#471)

feat: migrate all message to messageId

---

package.json

chore: avoid recursion in `format`/`lint`

---

index.js

Remove `name` from eslintrc config. It is only ok on the flat config.
Fixes #489.

fix: remove `name` from eslintrc config; fixes #489

---

README.md
docs/rules/prefer-await-to-callbacks.md
rules/prefer-await-to-callbacks.js

Added rule details for `prefer-await-to-callbacks`.
Fixes #118.
(Adapted from https://github.com/eslint-community/eslint-plugin-promise/pull/199 )

docs: add for `prefer-await-to-callbacks`; fixes #118

---

__tests__/always-return.js
rules/always-return.js

fix(`always-return`): treat process.exit() or process.abort() as an acceptable "return"
Fixes #451
Don't treat `process.exit()` or `process.abort()` as normal call expressions but treat them as returns.

fix(`always-return`): treat process.exit() or process.abort() as an acceptable "return"

---

__tests__/prefer-await-to-then.js
docs/rules/prefer-await-to-then.md
rules/prefer-await-to-then.js

feat: add `strict` option to disallow `then` or `catch` following `await` or `yield`
Fixes #294
Added a `strict` option which disallows `then` or `catch` following `await` or `yield`.

feat: add `strict` option to disallow `then` or `catch` following `await` or `yield`

---

README.md
docs/rules/avoid-new.md
docs/rules/no-callback-in-promise.md
rules/avoid-new.js
rules/no-callback-in-promise.js

Recommended `util.promisify` over `pify`.
Fixes #210.

docs: recommend `util.promisify` instead of pify

---

.github/workflows/ci.yml
package-lock.json
package.json

**What changes did you make?**
This simply updates the CI and package.json to run the tests against the node versions that ESLint v9 supports
BREAKING CHANGE: Requires Node.js: `^18.18.0 || ^20.9.0 || >=21.1.0`

chore!: Update node versions to align with eslint v9

---

.github/workflows/ci.yml
package-lock.json
package.json

see https://github.com/eslint-community/eslint-plugin-promise/pull/484#issuecomment-2246887433
Reverts eslint-community/eslint-plugin-promise#504
BREAKING CHANGE: Requires Node.js: ^18.18.0 || ^20.9.0 || >=21.1.0

feat!: Update node versions to align with eslint v9

---

.eslintrc.json
.husky/pre-commit
README.md
__tests__/index.js
package-lock.json
package.json
rules/always-return.js
rules/no-multiple-resolved.js
rules/no-nesting.js
rules/no-new-statics.js
rules/param-names.js

1. Bumped all packages (except eslint) to the latest version.
1. Replaced `eslint-plugin-node` with `eslint-plugin-n`
(#471)

chore: bump dev dependencies

---

.github/workflows/format.yml
docs/rules/avoid-new.md

This PR fixes the format.yml workflow.
Currently that workflow seems to always be ignored.

chore: fix format.yml

---

__tests__/catch-or-return.js
__tests__/prefer-await-to-then.js
rules/catch-or-return.js
rules/lib/is-member-call-with-object-name
rules/prefer-await-to-then.js

Fixes #180
Do not report Cypress commands (e.g., `cy.get('sel').then()`) for `catch-or-return` and `prefer-await-to-then`.

feat(`catch-or-return`, `prefer-await-to-then`): do not report Cypress commands

---

README.md
__tests__/no-new-statics.js
__tests__/spec-only.js
docs/rules/spec-only.md
index.js
rules/lib/is-promise.js
rules/lib/promise-statics.js
rules/spec-only.js

Add a new rule `spec-only` to check for non-spec Promise methods
Fixes #46.

feat: new rule `spec-only` to check for non-spec Promise methods

---

README.md

The CI badge wasn't working due to wrong casing of the `ci.yml` file
I changed the casing in the markdown

docs: fixes the CI readme badge

---

.github/workflows/compliance.yml

To assist #508 / #506 by ensuring that PR-title's are always valid conventional commit format before merging
Added a pinned [mtfoley/pr-compliance-action](https://github.com/mtfoley/pr-compliance-action) similar to what I use at eg. neostandard: https://github.com/neostandard/neostandard/blob/main/.github/workflows/compliance.yml

ci: add pr title format validation

---

__tests__/catch-or-return.js
docs/rules/catch-or-return.md
rules/catch-or-return.js

Added an `allowThenStrict` option which will fail on `then(fn1, fn2)` but pass on `then(null, fn)`
Also cleaned up the `allowThen` docs and tests.
Closes #52

feat(catch-or-return): add `allowThenStrict` option

---

__tests__/always-return.js
docs/rules/always-return.md
rules/always-return.js

Adds `ignoreAssignmentVariable` as discussed in https://github.com/eslint-community/eslint-plugin-promise/pull/518#issuecomment-2260068048

feat(always-return): add `ignoreAssignmentVariable` option

---

__tests__/no-callback-in-promise.js
docs/rules/no-callback-in-promise.md
rules/no-callback-in-promise.js

- feat(`no-callback-in-promise`): add `timeoutsErr` option; fixes #167
- fix(`no-callback-in-promise`): ensure timeouts do not err (by default); fixes #220

feat(`no-callback-in-promise`): add `timeoutsErr` option

---

__tests__/no-new-statics.js
__tests__/valid-params.js
docs/rules/always-return.md
docs/rules/no-native.md
docs/rules/valid-params.md
rules/valid-params.js

Adds an `exclude` option to `valid-params`. Allows use of non-standard methods, e.g., Bluebird `catch`.
Also refactors a few instances of array join into ES6 templates
Fixes #127

feat(`valid-params`): add `exclude` option

---

README.md
__tests__/prefer-catch.js
docs/rules/prefer-catch.md
index.js
package-lock.json
package.json
rules/fix/remove-argument.js
rules/lib/parentheses.js
rules/prefer-catch.js

Adds new rule `prefer-catch` to prefer `catch` over `then(a, b)` or `then(null, b)`.
Closes #217.

feat: new rule `prefer-catch`

---

__tests__/no-callback-in-promise.js
rules/no-callback-in-promise.js

Fixes regression with false triggering by callback
Fixes #572

fix(`no-callback-in-promise`): false triggering of callback

---

__tests__/no-promise-in-callback.js
docs/rules/no-promise-in-callback.md
rules/lib/is-inside-callback.js
rules/no-promise-in-callback.js

For `no-promise-in-callback`, add an `exemptDeclarations` option to prevent reporting when the promise is within function declarations.
Fixes #445

feat(`no-promise-in-callback`): add `exemptDeclarations` option
