- rules/always-catch.js
- rules/param-names.js
Trying to add this to `standard` and caught some crashes.
> Fix crash on real-world code

- index.js
I tried to use this against a project, but since I want to use the no-native rule I just got an error against every file:
```
1:1  error  Definition for rule 'promise/no-native' was not found  promise/no-native
```
Can this be merged and a new version pushed up to npm please?
> Actually include no-native in the rules

- package.json
- rules/always-catch.js
- rules/always-return.js
- rules/catch-or-return.js
- rules/no-native.js
- rules/param-names.js
- use ESLint 3 rule format: http://eslint.org/blog/2016/07/eslint-new-rule-format
- specify ESLint ^2.10 or ^3 as a peerDependency to help `npm` users identify compatibility issues
- ~~specify Node.js 4 as the minimum: http://eslint.org/docs/user-guide/migrating-to-3.0.0#dropping-support-for-nodejs--4~~
> bumps deps; use ESLint 3 rule format

- rules/always-return.js
- test/always-return.test.js
> fix always-return error with shortcircuit syntax

- README.md
- rules/catch-or-return.js
- rules/lib/is-promise.js
- rules/no-return-wrap.js
- test/no-return-wrap.js
Anyone want to give some comments on this before it goes in?
> rule: no-return-wrap (fixes #11)

- rules/always-return.js
- test/always-return.test.js
PR for Issue #34. Handle unreachable return or throw.
> Fixes #34. Handle unreachable return or throw.

- rules/always-return.js
- test/always-return.test.js
Potential fix for #31. I'm not sure what side effects this would have, but it seems like it works. I've tested it on some other projects. Thoughts?
> Potential fix for #31

- README.md
- index.js
Can be added using
``` yml
extends: plugin:promise/recommended
```
Resolves #53
> Add recommended configuration

- README.md
Makes the README look that much prettier.
> doc: fix right alignment of the rules table

- rules/lib/is-callback.js
- rules/lib/is-named-callback.js
- rules/no-callback-in-promise.js
- test/no-callback-in-promise.js
see https://github.com/xjamundx/eslint-plugin-promise/issues/43 for more details
> adding exceptions to no-callback-in-promise

- .travis.yml
Opening this PR to see if you're open to testing on a couple of newer versions of Node in addition to Node 4.
> ci: test on Node 6 and Node 8

- index.js
- rules/always-return.js
- rules/avoid-new.js
- rules/catch-or-return.js
- rules/lib/has-promise-callback.js
- rules/lib/is-callback.js
- rules/lib/is-inside-callback.js
- rules/lib/is-inside-promise.js
- rules/lib/is-named-callback.js
- rules/lib/is-promise.js
- rules/no-callback-in-promise.js
- rules/no-nesting.js
- rules/no-promise-in-callback.js
- rules/no-return-in-finally.js
- rules/param-names.js
- rules/prefer-await-to-callbacks.js
- rules/prefer-await-to-then.js
- test/no-return-in-finally.js
I noticed that some files opted into strict mode and others do not. Would you be open to enabling strict mode in all other files as long as tests continue to pass?
> refactor: enable strict mode in all files

- README.md
Via https://github.com/xjamundx/eslint-plugin-promise/pull/85#issuecomment-363852306
@xjamundx I've added you to the maintainers section since this is your repo. I know you said you have limited time to contribute each week in the linked comment above, so let me know if you'd like to be in the Maintainers section of the README or not - either way is cool and I'll be glad to update. 👍
> docs(readme): add maintainers section

- CONTRIBUTING.md
- package.json
Resolves #84
Thank you [ava](https://github.com/avajs/ava/blob/master/contributing.md) for a nice contributing doc that I based most of this off. 🎉  I think this is a good start for how to contribute and some basics on getting set up locally. 👍
> docs: add CONTRIBUTING.md

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
Resolves #87 
Issue template modified from [atom/atom](https://github.com/atom/atom/blob/master/ISSUE_TEMPLATE.md). New contributing section modified from [avajs/ava](https://github.com/avajs/ava/blob/master/contributing.md).
> docs: add GitHub issue template

- .github/PULL_REQUEST_TEMPLATE.md
Resolves #88 
This is a stripped-down version of [eslint/eslint](https://github.com/eslint/eslint/blob/master/.github/PULL_REQUEST_TEMPLATE.md)'s PR template. It's a start, can always modify later on if it would be helpful.
> docs: add GitHub pull request template

- .eslintrc.json
This commit adds [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node) to our codebase's ESLint config. The [`no-unsupported-features`](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md) rule is helpful for ensuring our source code is written using Node 4 supported features, especially if you're developing and running tests with Node 8.
> style(lint): add eslint-plugin-node

- README.md
- rules/param-names.js
- test/param-names.test.js
> feat(fixer): add fixer for param-names

- CHANGELOG.md
**Do not merge yet** - this is a placeholder for updating the changelog for v3.7.0. I'd like to merge the following PRs and update the changelog before releasing early in the next week:
> docs(changelog): prepare for v3.7.0

- CHANGELOG.md
Getting ready to ship v3.8.0 and updating the changelog with the changes since v3.7.0.
> docs(changelog): prepare for v3.8.0

- .eslintrc.json
- README.md
- package-lock.json
- package.json
- rules/always-return.js
This PR swaps out a few unused ESLint configs for the `eslint:recommended` config.
> chore: simplify linter configuration

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .prettierignore
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/rules/valid-params.md
- package-lock.json
- package.json
This PR updates Prettier to v1.13.0. See the [blog post](https://prettier.io/blog/2018/05/23/1.13.0.html) for details.
> chore(package): update to prettier@1.13.0

- package-lock.json
- package.json
This PR updates ESLint plugin dependencies + Prettier.
> chore(package): update eslint plugins

- __tests__/always-return.js
- __tests__/catch-or-return.js
- __tests__/no-callback-in-promise.js
- __tests__/no-return-wrap.js
- __tests__/prefer-await-to-then.js
- package-lock.json
- package.json
As requested by @voxpelli in https://github.com/xjamundx/eslint-plugin-promise/pull/219#issuecomment-979891417
> chore: update dependencies to latest minor version

- README.md
- package-lock.json
- package.json
- rules/no-native.js
- Documentation update
- Bug fix
1. I fixed the issue of `promise/no-native` failing when using `@typescript-eslint/parser`.
2. I added myself to the list of contributors in `package.json` and the list of maintainers in `README.md`.
3. I ran `npm audit fix` to fix security vulnerabilities and `npx browserslist@latest --update-db` to update the browsers list.
> fix: default to leftToBeResolved, fixes #205

- .github/workflows/CI.yml
Should have been included in #379 🙈😅
> fix(CI): fix release script

- package-lock.json
- package.json
> chore: add pkg.funding

- index.js
Adds a `name` property to the project's two configs as [recommended by ESLint docs](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions). This property can be used in tooling like the [ESLint Config Inspector](https://github.com/eslint/config-inspector).
> feat: add `name` property to configs (for use with tooling)

- .github/workflows/ci.yml
- package-lock.json
- package.json
Reverts eslint-community/eslint-plugin-promise#484
> Revert "chore!: Update node versions to align with eslint v9"

- .eslint-doc-generatorrc.js
Added a missing 'use strict' directive to the only CJS file in this repo without one.
> chore: add missing `'use strict'` directive
